spring.application.name=api
server.port=8080
api.security.token.secret=${JWT_SECRET}
spring.web.error.include-stacktrace=never
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
cloudflare.r2.account-id=${CLOUDFLARE_TOKEN}
cloudflare.r2.access-key=${CLOUDFLARE_ACCESS_KEY_ID}
cloudflare.r2.secret-key=${CLOUDFLARE_SECRET_ACCESS_KEY}
cloudflare.r2.bucket=${CLOUDFLARE_BUCKET_NAME}
cloudflare.r2.public-url=${CLOUDFLARE_PUBLIC_URL}