spring.application.name=api
server.port=8080

api.security.token.secret=${JWT_SECRET}

spring.web.error.include-stacktrace=never

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.highlight_sql=false
spring.jpa.show-sql=false
spring.sql.init.mode=always

logging.level.org.hibernate.orm.jdbc.bind=OFF

spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}

cloudflare.r2.account-id=${CLOUDFLARE_TOKEN}
cloudflare.r2.access-key=${CLOUDFLARE_ACCESS_KEY_ID}
cloudflare.r2.secret-key=${CLOUDFLARE_SECRET_ACCESS_KEY}
cloudflare.r2.bucket=${CLOUDFLARE_BUCKET_NAME}
cloudflare.r2.public-url=${CLOUDFLARE_PUBLIC_URL}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false