package com.letraaletra.api.features.audit.domain;

public enum AuditEventType {
    WALLET_CREDITED,
    WALLET_DEBITED,

    COSMETIC_ACQUIRED,
    COSMETIC_REVOKED,
    COSMETIC_EQUIPPED,
    COSMETIC_UNEQUIPPED,

    ITEM_ACQUIRED,
    ITEM_REMOVED,
    ITEM_EQUIPPED,
    ITEM_UNEQUIPPED,
    ITEM_CONSUMED,
    ITEM_QUANTITY_CHANGED,

    MATCH_STARTED,
    MATCH_ENDED,
    ROOM_CLOSED_INACTIVITY,
    PLAYER_REMOVED_INACTIVITY,
    MATCHMAKING_PAIRED,

    CATALOG_CHANGED,

    TICKET_CREATED,
    TICKET_RESOLVED,

    COMMAND_FAILED
}
