name: Ping Api

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping-loop:
    runs-on: ubuntu-latest
    steps:
      - name: Loop de Pings a cada 30 segundos
        run: curl -I https://letra-a-letra-api.onrender.com/actuator/health